language: node_js

cache: npm

before_install:
  - mysql -e 'CREATE DATABASE test_db;'

before_script:
  - npm i -g typescript
  - tsc

node_js:
  - '16'

services:
  - mysql

notifications:
  email:
    on_success: never
    on_failure: always
